// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: activation/activation.proto

package activation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActivationTokenServiceClient is the client API for ActivationTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivationTokenServiceClient interface {
	GenerateForUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type activationTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivationTokenServiceClient(cc grpc.ClientConnInterface) ActivationTokenServiceClient {
	return &activationTokenServiceClient{cc}
}

func (c *activationTokenServiceClient) GenerateForUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/activation.ActivationTokenService/GenerateForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivationTokenServiceServer is the server API for ActivationTokenService service.
// All implementations must embed UnimplementedActivationTokenServiceServer
// for forward compatibility
type ActivationTokenServiceServer interface {
	GenerateForUser(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedActivationTokenServiceServer()
}

// UnimplementedActivationTokenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedActivationTokenServiceServer struct {
}

func (UnimplementedActivationTokenServiceServer) GenerateForUser(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateForUser not implemented")
}
func (UnimplementedActivationTokenServiceServer) mustEmbedUnimplementedActivationTokenServiceServer() {
}

// UnsafeActivationTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivationTokenServiceServer will
// result in compilation errors.
type UnsafeActivationTokenServiceServer interface {
	mustEmbedUnimplementedActivationTokenServiceServer()
}

func RegisterActivationTokenServiceServer(s grpc.ServiceRegistrar, srv ActivationTokenServiceServer) {
	s.RegisterService(&ActivationTokenService_ServiceDesc, srv)
}

func _ActivationTokenService_GenerateForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivationTokenServiceServer).GenerateForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activation.ActivationTokenService/GenerateForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivationTokenServiceServer).GenerateForUser(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivationTokenService_ServiceDesc is the grpc.ServiceDesc for ActivationTokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivationTokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activation.ActivationTokenService",
	HandlerType: (*ActivationTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateForUser",
			Handler:    _ActivationTokenService_GenerateForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activation/activation.proto",
}
