get http://localhost:5006/v1/task/6448958b96118a48b722fd15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNjgyNTY0ODI2fSwiVXNlcklEIjoiNjQ0ODk0ZTA2NzAzY2ZiNDM0OWIzZDk4In0.cI4znexFvs9UOMCn3qMA2Wq8A1Vb5l5wTt3jDPXCCMY

