
post http://localhost:5006/v1/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNjgyOTg2MzQzfSwiVXNlcklEIjoiNjQ0ZjAwMDFjNDJiMTY2NDM1YWI0N2FjIn0.G4HuOyPKR4XKCTCOPoY1tu4fPWr2hf5sCmYA0XJIpTM

{
	"name"     :"laundry",
	"details"  :"quickly",
	"priority" :"high",
	"category" :"chores"
}