
post http://localhost:5006/v1/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNjgyNDUzMTA1fSwiVXNlcklEIjoiNjQ0NmQ5OGNiODk3ODQwYjg1Y2VlYzE3In0.2XRGOo0v9VbA8mAFKRIidWotnMRfct2k_QcusdwJC7A

{
	"name"     :"laundry",
	"details"  :"quickly",
	"priority" :"high",
	"category" :"chores"
}