put http://localhost:5006/v1/task

{
	"taskId": "643d23f3c3fd7833969ac277",
	"userId"   : "507f1f77bcf86cd799439011",
	"name"     : "laundry",
	"details"  : "quickly",
	"priority" : "medium",
	"category" : "chores"
}